#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export ANDROID_HOME='~/00.DevCenter/Android/android-studio/sdk'

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /Users/tudor/Library/Android/sdk/{platform-tools,tools}
  /Users/tudor/Library/Flutter/flutter/bin
  $path
)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
