#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# The next line updates PATH for the Google Cloud SDK.
source '/Users/tudor/Library/google-cloud-sdk/path.zsh.inc'

# The next line enables bash completion for gcloud.
autoload -U compinit compdef
compinit
source '/Users/tudor/Library/google-cloud-sdk/completion.zsh.inc'

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/tudor/.gvm/bin/gvm-init.sh" ]] && source "/Users/tudor/.gvm/bin/gvm-init.sh"
